import os
from rdkit import Chem
from Bio.PDB import PDBParser

def parse_mol2(file_path):
    """Parse a MOL2 file and return atom symbols and coordinates."""
    mol = Chem.MolFromMol2File(file_path)
    if mol is not None:
        print(f"Success to read molecule from MOL2 file: {file_path}")
        # raise ValueError(f"Failed to read molecule from MOL2 file: {file_path}")
    else:
        atoms = []
        coords = []
        smiles = None
        with open(file_path, 'r',errors='ignore') as f:
            lines = f.readlines()

            for line in lines:
                parts = line.split()
                # check for atom information line: length should be more than 4 and parts[3] should be an symbol
                if len(parts) >= 4 and parts[3].isalpha():
                    try:
                        x, y, z = float(parts[0]), float(parts[1]), float(parts[2])
                        atom_symbol = parts[3]
                        atoms.append(atom_symbol)
                        coords.append((x, y, z))
                    except ValueError:
                        continue
                if line.startswith('M END'):
                    break
        return atoms, coords

    conf = mol.GetConformer()
    atoms = [atom.GetSymbol() for atom in mol.GetAtoms()]
    coords = [conf.GetAtomPosition(i) for i in range(mol.GetNumAtoms())]
    return atoms, coords


def parse_pdb(file_path):
    """Parse a PDB file and return atom symbols and coordinates."""
    parser = PDBParser(PERMISSIVE=1)
    structure = parser.get_structure('protein', file_path)
    atoms = []
    coords = []
    for model in structure:
        for chain in model:
            for residue in chain:
                for atom in residue:
                    atoms.append(atom.element)
                    coords.append(atom.coord)
    return atoms, coords


def save_xyz(file_path, atoms, coords):
    """Save atoms and coordinates to an XYZ file."""
    with open(file_path, 'w') as f:
        f.write(f"{len(atoms)}\n")
        f.write("Generated by script\n")
        for atom, coord in zip(atoms, coords):
            f.write(f"{atom} {coord[0]:.6f} {coord[1]:.6f} {coord[2]:.6f}\n")


def process_folder(base_folder, sub_dirs, output_folder):
    """Process each subfolder and convert ligand.mol2(sdf也是一样) and pocket.pdb to XYZ format."""
    for sub_dir in sub_dirs:
                protein_file = os.path.join(base_folder, sub_dir)
                if os.path.exists(protein_file):
                    protein_list=os.listdir(protein_file)
                    for protein_name in protein_list:
                        protein_path=os.path.join(protein_file,protein_name)
                        try:
                                pocket_atoms, pocket_coords = parse_pdb(protein_path)
                                output_subfolder = os.path.join(output_folder, sub_dir)
                                os.makedirs(output_subfolder, exist_ok=True)
                                protein_name=protein_name.replace('.pdb','')
                                output_pocket_xyz = os.path.join(output_subfolder, f"{protein_name}.xyz")
                                save_xyz(output_pocket_xyz, pocket_atoms, pocket_coords)
                                print(f"Saved pocket XYZ: {output_pocket_xyz}")
                        except Exception as e:
                                print(f"Error processing {protein_file}: {e}")




# 设置输入和输出文件夹路径
base_folder = 'DPI_data_for_xyz/proteins'  # 修改为实际的输入文件夹路径
output_folder = 'DPI_xyz/DPI_proteins_xyz'  # 修改为实际的输出文件夹路径
sub_dirs = os.listdir(base_folder)

# 处理文件夹
process_folder(base_folder, sub_dirs, output_folder)